# Generated by Django 4.1.7 on 2023-03-07 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='address',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='companyName',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='eMail',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='job',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='personId',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
