# Generated by Django 4.1.7 on 2023-03-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dataschema_address_dataschema_companyname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschema',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='companyName',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='eMail',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='job',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='personId',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='x',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='y',
            field=models.BooleanField(default=False),
        ),
    ]
