# Generated by Django 4.1.7 on 2023-03-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
