# Generated by Django 4.1.7 on 2023-03-11 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataschema',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='x',
        ),
        migrations.RemoveField(
            model_name='dataschema',
            name='y',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='address',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='companyName',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='eMail',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='fullName',
            field=models.CharField(max_length=30, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='job',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='dataschema',
            name='personId',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='dataschema',
            name='phoneNumber',
            field=models.CharField(max_length=10, null='True'),
            preserve_default='True',
        ),
    ]
