# Generated by Django 4.1.7 on 2023-03-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_table_dataschema_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='personId',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='table',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.table'),
        ),
    ]
