# Generated by Django 4.1.7 on 2023-03-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_dataschema_personid_alter_dataschema_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataschema',
            name='phoneNumber',
            field=models.CharField(max_length=30, null='True'),
        ),
    ]
