# Generated by Django 4.1.7 on 2023-03-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_dataschema_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='col_ids',
            field=models.CharField(max_length=7, null='True'),
            preserve_default='True',
        ),
    ]
